/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeliveryProfileRouteImport } from './routes/delivery-profile'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSecurityRouteImport } from './routes/profile.security'
import { Route as ProfilePersonalRouteImport } from './routes/profile.personal'
import { Route as ProfilePaymentRouteImport } from './routes/profile.payment'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileAddressRouteImport } from './routes/profile.address'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryProfileRoute = DeliveryProfileRouteImport.update({
  id: '/delivery-profile',
  path: '/delivery-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentRoute = ProfilePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileAddressRoute = ProfileAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/delivery-profile': typeof DeliveryProfileRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/delivery-profile': typeof DeliveryProfileRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/delivery-profile': typeof DeliveryProfileRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/orders': typeof OrdersRouteWithChildren
  '/post-ad': typeof PostAdRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/staff-login': typeof StaffLoginRoute
  '/category/$slug': typeof CategorySlugRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/address': typeof ProfileAddressRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/delivery'
    | '/delivery-profile'
    | '/error'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/post-ad'
    | '/products'
    | '/profile'
    | '/staff-login'
    | '/category/$slug'
    | '/orders/$orderId'
    | '/product/$id'
    | '/profile/address'
    | '/profile/notifications'
    | '/profile/payment'
    | '/profile/personal'
    | '/profile/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/delivery'
    | '/delivery-profile'
    | '/error'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/post-ad'
    | '/products'
    | '/profile'
    | '/staff-login'
    | '/category/$slug'
    | '/orders/$orderId'
    | '/product/$id'
    | '/profile/address'
    | '/profile/notifications'
    | '/profile/payment'
    | '/profile/personal'
    | '/profile/security'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/delivery'
    | '/delivery-profile'
    | '/error'
    | '/login'
    | '/order-success'
    | '/orders'
    | '/post-ad'
    | '/products'
    | '/profile'
    | '/staff-login'
    | '/category/$slug'
    | '/orders/$orderId'
    | '/product/$id'
    | '/profile/address'
    | '/profile/notifications'
    | '/profile/payment'
    | '/profile/personal'
    | '/profile/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  DeliveryProfileRoute: typeof DeliveryProfileRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PostAdRoute: typeof PostAdRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-profile': {
      id: '/delivery-profile'
      path: '/delivery-profile'
      fullPath: '/delivery-profile'
      preLoaderRoute: typeof DeliveryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/personal': {
      id: '/profile/personal'
      path: '/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payment': {
      id: '/profile/payment'
      path: '/payment'
      fullPath: '/profile/payment'
      preLoaderRoute: typeof ProfilePaymentRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/address': {
      id: '/profile/address'
      path: '/address'
      fullPath: '/profile/address'
      preLoaderRoute: typeof ProfileAddressRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ProfileRouteChildren {
  ProfileAddressRoute: typeof ProfileAddressRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfilePaymentRoute: typeof ProfilePaymentRoute
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAddressRoute: ProfileAddressRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfilePaymentRoute: ProfilePaymentRoute,
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  DeliveryProfileRoute: DeliveryProfileRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PostAdRoute: PostAdRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
